version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0
  cli: circleci/circleci-cli@0.1.7

jobs:
  publish:
    executor: cli/default
    steps:
      - checkout
      - run:
          command: echo export BUILD_VERSION=$(grep \"version\" package.json | cut -c 15- | rev | cut -c 3- | rev) >> $BASH_ENV
      - orb-tools/pack
      - orb-tools/validate
      - orb-tools/publish:
          orb-ref: leppis/tools@$BUILD_VERSION
          token-variable: CIRCLECI_DEV_API_TOKEN

workflows:
  main:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires: [orb-tools/lint]
      - publish:
          requires: [orb-tools/pack]
          filters:
            branches:
              only:
                - master
