version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  main:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires: [orb-tools/lint]
      - orb-tools/publish:
          requires: [orb-tools/pack]
          orb-path: src/orb.yml
          orb-ref: circleci/leppis@dev:beta
          publish-token-variable: $CIRCLECI_DEV_API_TOKEN
          validate: true
      # - orb-tools/publish:
      #     requires: [orb-tools/pack]
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     orb-path: src/orb.yml
      #     orb-ref: circleci/leppis@dev:${cat VERSION}
      #     publish-token-variable: $CIRCLECI_DEV_API_TOKEN
      #     validate: true
