description: Build job

parameters:
  build-path:
    description: Path to where the build files will be
    default: dist
    type: string
  compress:
    description: If the build process should run the command `yarn compress`
    default: false
    type: boolean
  build-steps:
    description: Steps to build the project
    default:
      - run: yarn build
    type: steps
  cache-version:
    description: Version of the cache. Usage to bump the deps cache key
    default: "v1"
    type: string
  notify-slack:
    default: false
    description: "Notify slack on job status"
    type: boolean

executor: node

steps:
  - checkout
  - restore-yarn:
      cache-version: << parameters.cache-version >>
  - steps: << parameters.build-steps >>
  - when:
      condition: << parameters.compress >>
      steps:
        - run: yarn compress
  - persist_to_workspace:
      paths: << parameters.build-path >>
      root: .
  - when:
      control: << parameters.notify-slack >>
      steps:
        - slack/status:
            fail_only: true
